### ISSUE TITLE
Can be unable to re-enter Beast's Den

### ISSUE THREAD

**Issue by mDuo13** [Ijwu/Archipelago.HollowKnight#114]
With careless use of bench-warping, it's possible to get locked out of Beast's Den.

Settings: Dreamers non-randomized. (I'm unsure what happens if dreamers are randomized; possibly picking up Herrah early also disables the trap bench, locking you out of Beast's Den?)

To reproduce:

1. Enter Beast Den
2. Collect Herrah
3. Bench warp out immediately (do not use the real Beast's Den bench or open the one-way path near the entrance)

Result: the trap bench no longer activates, but there's no way back into Beast's Den.
Workaround: In benchwarp mod, enable all benches and warp to Beast's Den bench.

**Comment by dewiniaid** [comment]
[ReusableBeastsDenEntrance](https://github.com/homothetyhk/HollowKnight.ItemChanger/blob/master/ItemChanger/Modules/ReusableBeastsDenEntrance.cs/#L9) is a default IC module, so this should not be happening unless something is mucking with that.  We don't touch default IC modules... so need some additional testing on this one.

**Comment by BadMagic100** [comment]
Fixed in ItemChanger as of most recent release https://github.com/homothetyhk/HollowKnight.ItemChanger/commit/cc0c4384b750f2e58eda34cbd6528e06e97ca4b0

**Comment by Ijwu** [comment]
> Fixed in ItemChanger as of most recent release [homothetyhk/HollowKnight.ItemChanger@cc0c438](https://github.com/homothetyhk/HollowKnight.ItemChanger/commit/cc0c4384b750f2e58eda34cbd6528e06e97ca4b0)

Thank you for the info!

Does this require any changes on our part to ensure the IC module is working and this problem is resolved? I see it has a new arg, which is `false` by default.

**Comment by BadMagic100** [comment]
It should not require a change, but there is a behavioral change in how beast's den works that you may choose to correct for. The parameter only controls whether or not the beast's den hardsave should be disabled.

Before, the hardsave was always disabled, as the approach to keep the trap bench active was to prevent the cocoon from doing anything. This removed the hardsave probably not entirely intentionally as a side effect. However it also failed to prevent vanilla Herrah from removing the trap bench. The current implementation just overrides the value indicating whether the trap bench is active, so the hardsave is now configurable

**Comment by Ijwu** [comment]
I think it's safe to say this is closable as something that is fixed with a client update of dependencies. That may or may not occur in the future.
