### ISSUE TITLE
Divine should probably copy Rando4 behavior for player sanity

### ISSUE THREAD

**Issue by Ijwu** [Ijwu/Archipelago.HollowKnight#16]
Divine seems to take your money and give you charms... It is not quite Rando4 behavior and in this case I think we should copy Rando4.

**Comment by BadMagic100** [comment]
In vanilla, divine takes your fragile charm, then you pay a stupid amount of geo to get it back as unbreakable.

In rando/IC, you to to Divine wearing a fragile or unbreakable charm, and you prepay a fraction of the cost (in rando, 450 for greed, 600 for heart, and 750 for strength) to get whatever item is placed there.

I believe (but could be wrong) that the concern reported at the testing was that divine was free. Actually, for me one of divine's items was free while another had the normal cost. Possibly related to #9 and #21
