### ISSUE TITLE
Basin fountain should cost money

### ISSUE THREAD

**Issue by Ijwu** [Ijwu/Archipelago.HollowKnight#21]
Basin fountain doesn't cost money for some people, although this is possibly inconsistent.

**Comment by flibber-hk** [comment]
If this is inconsistent, that means that it is affecting people who play with NPC Item Dialogue disabled (it's in the mod menu under Location Settings, I think - the non-default option). The fix for that will probably be the same as the fix for #9.

**Comment by Ijwu** [comment]
My hunch was that I was placing a new placement on the basin (and stag stations, since you referred to #9) and just not including a cost. I heard from one person that the basin cost money but most others said it did not.

**Comment by flibber-hk** [comment]
If it helps, it's semi-automated [here](https://github.com/homothetyhk/RandomizerMod/blob/master/RandomizerMod/IC/CostConversion.cs) in Rando (the costs are hardcoded elsewhere). I expect you'll get the same issue with Cornifer locations, too.

**Comment by Berserker66** [comment]
+1 for inconsistent, I had to pay 3000 geo
