### ISSUE TITLE
Sort item placements by ascending cost order when placed into CostChestPlacements

### ISSUE THREAD

**Issue by Ijwu** [Ijwu/Archipelago.HollowKnight#25]
This would ensure that they appear in the resulting lore tablet for Grubfather or Seer in order of price.

**Comment by Ijwu** [comment]
This can happen on the server-side. Berserker will have the items sent to me in cost order for grub, egg, and seer shops. Geo shop costs are randomized on the client side and so I will need to alter geo cost order for Iselda, Sly, Sly_Key, Leg_Eater, and Salubra (but not Salubra_Charms.

**Comment by Ijwu** [comment]
Berserker made the change on the server, however they are showing up in descending order in the game. This must be due to how item placements are ordered internally. I should be able to flip this after some refactoring.

Depends on #1 and #5.

**Comment by dewiniaid** [comment]
#85 addresses this simply by reversing the entire item list before beginning placement.
