### ISSUE TITLE
Leg Eater doesn't repair broken charms

### ISSUE THREAD

**Issue by RaptorJesus2001** [Ijwu/Archipelago.HollowKnight#26]
[Player.log](https://github.com/Ijwu/Archipelago.HollowKnight/files/8405216/Player.log)
[ModLog.txt](https://github.com/Ijwu/Archipelago.HollowKnight/files/8405217/ModLog.txt)

What was expected to occur: Leg Eater repairs fragile charms that are broken

What actually occurred: Leg Eater has no way to purchase broken charm repair

Steps to reproduce: 
1. Die with any fragile charm equipped
2. Visit Leg Eater

**Comment by Ijwu** [comment]
Thanks, will look into it.

**Comment by Ijwu** [comment]
I have been informed on HK Modding Discord that this requires the LegEaterRepair item to be placed in Leg Eater's placement. This can be done by altering ShopLocation.defaultShopItems when placing that particular shop.
