### ISSUE TITLE
Don't randomize shop costs for vanilla shop placements.

### ISSUE THREAD

**Issue by Ijwu** [Ijwu/Archipelago.HollowKnight#31]
If an item is not randomized and it normally belongs in a shop, do not randomize its Geo price.

Example: Turning off RandomizeCharms should not randomize geo costs of charms in Leg Eater's shop.

This might require tracking all the items which are within a shop by default. It could also mean not placing the vanilla item and then including the DefaultShopItem in the ShopLocation to have that shop's vanilla items.

**Comment by dewiniaid** [comment]
Fixed in hk-dev
