### ISSUE TITLE
Server info entry screen changes

### ISSUE THREAD

**Issue by KonoTyran** [Ijwu/Archipelago.HollowKnight#45]
Can we change the defaults on the server entry screen to default to 'Archipelago.gg' and if possible increase the length of it so longer addresses can fit in there without scrolling.

Same for the slot name entry, blank out the default and lengthen it for longer names to be visible without scrolling.

**Comment by Ijwu** [comment]
I don't believe I can increase the actual width of the text field, but I will explore it. Defaults are simple changes, though. Great first issue for anyone looking to dive in.
