### ISSUE TITLE
Sever side: mark "currency" items with skip_in_prog_balancing = True

### ISSUE THREAD

**Issue by KonoTyran** [Ijwu/Archipelago.HollowKnight#46]
All grubs
all essence drops
All charms except the following:
- Glowing Womb
- Weaversong
- Grubberfly's Elegy
- Grimm child
- Spore shroom
- Defenders crest

Should be marked with 'skip_in_prog_balancing = True' as they are all types of currencies when it comes to unlocking checks and will fill up lower spheres very quickly.

**Comment by dewiniaid** [comment]
Dashmaster and Sprintmaster can also be logically required.  Notably, Dashmaster can sometimes be required for the Greenpath Hallownest Seal east of Sheo, and the combination of them can be logically required for the crusher puzzle in CPeaks.

These two cases are pretty rare though.

**Comment by KonoTyran** [comment]
They are still progression items and are taken account for in logic, they just won't be moved by progression balancing with this change.
