### ISSUE TITLE
Completion goal should be customizable and not simply "Any ending"

### ISSUE THREAD

**Issue by dewiniaid** [Ijwu/Archipelago.HollowKnight#48]
Some work towards this:

Like LTTP/OOT, we'd probably want the player's actual goal to be displayed in game somewhere.  My idea is the HK memorial fountain in City (scene ruins1_27), which I feel is progression-wise on par with the Pyramid sign in LTTP/Adult ToT in OOT.  The text on that fountain can be edited with (vanilla text included):

```csharp
ItemChanger.Events.AddLanguageEdit(new ItemChanger.LanguageKey("Prompts", "FOUNTAIN_PLAQUE_TOP"), (ref string s) => { s = "Memorial to the");
ItemChanger.Events.AddLanguageEdit(new ItemChanger.LanguageKey("Prompts", "FOUNTAIN_PLAQUE_MAIN"), (ref string s) => { s = "Hollow Knight"; });
ItemChanger.Events.AddLanguageEdit(new ItemChanger.LanguageKey("Prompts", "FOUNTAIN_PLAQUE_DESC"), (ref string s) => { s = "In the Black Vault far above.&lt;br&gt;Through its sacrifice Hallownest lasts eternal.");
```

My thought is we can initially support the following goals:
- Any ending (as it is now), aka Any%.  The first ending is canonically known as "The Hollow Knight"
  - Reach the end credits scene.
  - Note: The ending cutscene scene is "Cinematic_Ending_A"

- Sealed Siblings
  - Reach the end credits scene with 3 Dreamers + Voidheart.  Note that someone could technically go beat Absrad and never do the true Sealed Siblings ending, but that requires beating an even harder HK along the way so... that's fine.
  - Note: The ending cutscene scene is "Cinematic_Ending_B"
  
 - Radiance ("Dream No More")
   - Reach the end credits scene after having entered scene "Dream_Final" more recently than entering "Room_Final_Boss_Core"
   - Note: The ending cutscene scene is "Cinematic_Ending_C"

 - AbsRad ("Embrace the Void")
   - The ending cutscene is probably "Cinematic_Ending_D" and/or "Cinematic_Ending_E", depending on if Flower quest has been completed, but I'm not easily able to test these.

**Comment by BadMagic100** [comment]
If you're looking to test embrace the void ending, you could like, benchwarp unlock all then DebugMod with invincibility, noclip, and instakill to (somewhat) quickly knock out all the bosses and pantheons - even then it's a bit of a time commitment though.
