### ISSUE TITLE
Placements should be returned as a whole IEnumerable and be placed all at once

### ISSUE THREAD

**Issue by Ijwu** [Ijwu/Archipelago.HollowKnight#5]
Placements are placed individually right now as they are scouted. PlaceItem() is called per item and then PlaceItem() registers the placement with ItemChanger. This could change so that PlaceItem() is replaced with a method which returns _all_ item placements and then registers them with ItemChanger all at once.

**Comment by dewiniaid** [comment]
Fixed in 0.0.3
