### ISSUE TITLE
Force dreamers to be local, always

### ISSUE THREAD

**Issue by Ijwu** [Ijwu/Archipelago.HollowKnight#51]
Please vote on this issue by thumbs up reacting or thumbs down reacting.

The alternative to implementing this issue is having a YAML that puts dreamers under the local_items setting. This can also be done for randomized game settings using triggers to automatically handle this when you roll a Hollow Knight game.

**Comment by Berserker66** [comment]
third option to RandomizeDreamers that shuffles them local only?

**Comment by BadMagic100** [comment]
Forcing basically anything seems like a bad idea. Any flavor of option is great, seeing as local_items exists I don't feel any particular need for a change here. But berserker's idea above seems super reasonable as well

**Comment by dewiniaid** [comment]
I feel like local_items is already a fix for this and it doesn't need special handling otherwise.

Additionally, #48 (which I am working on) may alleviate part of the reason this is desired.

**Comment by dewiniaid** [comment]
Since the community has pretty much decided against this (and there is already an option to forcing it anyways), I'm closing this.
