### ISSUE TITLE
Dying while killing some bosses permanently deletes their drop

### ISSUE THREAD

**Issue by espeon65536** [Ijwu/Archipelago.HollowKnight#54]
It's possible to die after killing some bosses, such as the Soul Warriors in Soul Sanctum (since they fire projectiles and have other enemies with them). If that boss drops a Boss Geo item, then that item will be permanently lost when returning to the room after respawning. This seems like it might be an ItemChanger issue, but I'm opening it here because it renders the AP item there permanently uncheckable as well.

**Comment by BadMagic100** [comment]
I believe this issue was on the ItemChanger side (elegant soul warrior and gorgeous husk were notably affected). The soul warrior has been fixed, and gorgeous husk is either tracked to be fixed or fixed

**Comment by Ijwu** [comment]
Closing this issue and allowing the IC team to track this. If this re-occurs after IC fixes it or if it is determined this is not an IC bug, please re-open here.

Thank you!
