### ISSUE TITLE
Change font, if possible, on sign in screen to increase accessibility

### ISSUE THREAD

**Issue by Ijwu** [Ijwu/Archipelago.HollowKnight#55]
The current font is awful in terms of distinguishing capital letters from lowercase.

**Comment by dewiniaid** [comment]
An alternative might be to see if it's feasible to make slot name matching case-insensitive in AP, since HK is not the only game that lacks clearly distinguishable lower and uppercase.

**Comment by Ijwu** [comment]
I would leave things as-is in Archipelago serverside and see if there's an easy fix on the HK side first. Changing the font should not be overtly difficult.

Find a font that the game has cached and use CanvasUtil.GetFont() to get it then set it on the TextInputs, not too bad.
